### ISSUE TITLE
Добавить отзывы

### ISSUE THREAD

**Issue by Orhideous** [everypony/ponyFiction#39]
_From @tanriol on February 15, 2016 23:52_

Отзыв - промежуточная ступень между рассказом и комментарием.

- [ ] Пользователи могут оставлять отзывы на рассказы
- [ ] От одного пользователя принимается только один отзыв на каждый рассказ.
- [ ] Минимальный объём отзыва 150 слов
- [ ] Автор может редактировать свой отзыв первые 10 минут или до первого комментария (что раньше) (#31)
- [ ] У каждого отзыва есть своя независимая ветка комментариев (#23)
- [ ] У отзывов есть оценки, изменяемые по общим правилам (#32)
- [ ] Возможность переключаться между просмотром комментариев и отзывов (#22)
- [ ] Индикатор рейтинга отзыва, возможно, через цвет фона (#25)
- [ ] Сортировка отзывов по рейтингу / показ лучшего отзыва (#26)
- [ ] Изменение отзыва возможно раз в две недели.
- [ ] Любое изменение отзыва проходит премодерацию.

(входит в #5)

_Copied from original issue: RuFimFiction/ponyFiction#21_

**Comment by Orhideous** [comment]
_From @tanriol on February 22, 2016 19:3_

@WillWisp, с обоими правилами "один отзыв от пользователя на рассказ" и "редактирование 10 минут / до первого комментария" мы не получим жалоб на "я писал отзыв месяц назад, с тех пор я много думал и теперь считаю уже иначе, но я не могу ни изменить его, ни оставить новый"?

**Comment by Orhideous** [comment]
_From @EpicMan2 on February 22, 2016 19:16_

@tanriol, дабы обеспечить защиту от частой смены мнений, предлагаю либо создавать историю конкретного отзыва, либо поставить возможность менять отзыв раз в неделю.

**Comment by Orhideous** [comment]
_From @tanriol on February 22, 2016 19:47_

@EpicMan2, или можно наоборот... можешь оставить новый отзыв, но через месяц после предыдущего. Можно с дополнением "второй и далее отзыв всегда на премодерацию", если потребуется.

**Comment by Orhideous** [comment]
_From @idem-id on February 22, 2016 19:56_

@tanriol, месяц слишком большой срок, две недели вполне нормальный вариант

**Comment by Orhideous** [comment]
_From @WillWisp on March 22, 2016 15:52_

@tanriol Можем и получить, верно. Твоё предложение хорошее, если сократить до двух недель, то так и стоит сделать.
